version: 0.2
phases:
  install:
    commands:
      - npm install --prefix ./frontend
  pre_build:
    commands:
      - npm run lint --prefix ./frontend
  build:
    commands:
      - VUE_APP_BACKEND_URL=$BACKEND_URL npm run build --prefix ./frontend
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
cache:
  paths:
    - '**/node_modules/**/*'
