version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
