version: 0.2
phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew clean build -Pvaadin.productionMode -x test
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - ./build/libs/*.jar
    - ./appspec.yml
    - ./scripts/**
  discard-paths: yes
cache:
  paths:
    - /root/.gradle/caches/**/*
    - '**/node_modules/**/*'
