= 회원 관련 API

== 회원 가입

operation::member-register-post[snippets='http-request,http-response']

== 로그인

operation::member-login-post[snippets='http-request,http-response']

=== 로그인 실패

사용자 정보를 올바르게 입력하지 않은 경우

operation::member-login-post-forbidden[snippets='http-response']

== 비밀번호 초기화

operation::member-reset-password-post[snippets='http-request,http-response']

=== 비밀번호 초기화 실패

사용자 정보를 올바르게 입력하지 않은 경우

operation::member-reset-password-post-forbidden[snippets='http-response']

== 비밀번호 변경

operation::member-edit-password-post[snippets='http-request,http-response']

=== 비밀번호 변경 실패

기존 비밀번호를 올바르게 입력하지 않은 경우

operation::member-edit-password-post-forbidden[snippets='http-response']

== 인증 코드 생성

operation::member-authentication-code-post[snippets='http-request,http-response']

== 인증 코드 확인

operation::member-authenticate-email-post[snippets='http-request,http-response']

== 내 정보 조회

operation::member-me-get[snippets='http-request,http-response']

== 내 정보 변경

operation::member-information-patch[snippets='http-request,http-response']

== 회원 탈퇴

operation::member-withdraw-delete[snippets='http-request,http-response']

=== 회원 탈퇴 실패

사용자 정보를 올바르게 입력하지 않은 경우

operation::member-withdraw-delete-forbidden[snippets='http-response']
