= 회원 관련 API

== 회원 가입

operation::post/users/register[snippets='http-request,http-response']

== 로그인

operation::post/users/login[snippets='http-request,http-response']

=== 로그인 실패

operation::post/users/login/forbidden[snippets='http-request,http-response']

== 임시 비밀번호 발급

operation::post/users/reset-password[snippets='http-request,http-response']

=== 임시 비밀번호 발급 실패

사용자 정보를 올바르게 입력하지 않은 경우

operation::post/users/reset-password/forbidden[snippets='http-request,http-response']

== 비밀번호 변경

operation::post/users/edit-password[snippets='http-request,http-response']

=== 비밀번호 변경 실패

기존 비밀번호를 올바르게 입력하지 않은 경우

operation::post/users/edit-password/forbidden[snippets='http-request,http-response']

== 인증 코드 발송

operation::post/users/authentication-code[snippets='http-request,http-response']

== 인증 코드 확인

operation::post/users/authenticate-email[snippets='http-request,http-response']

== 내 정보 조회

operation::get/users/me[snippets='http-request,http-response']

== 내 정보 변경

operation::patch/users/information[snippets='http-request,http-response']
