export const FORM = {
  EMAIL_MAX_LENGTH: 255,
  NAME_MAX_LENGTH: 30,
  PHONE_NUMBER_MAX_LENGTH: 13,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 20,
  REFERENCE_URL_MAX_LENGTH: 255,
  GITHUB_USERNAME_MAX_LENGTH: 39,
  NOTE_MAX_LENGTH: 1000,
} as const;
