export const RECRUITMENT_STATUS = {
  RECRUITABLE: "RECRUITABLE",
  RECRUITING: "RECRUITING",
  UNRECRUITABLE: "UNRECRUITABLE",
  ENDED: "ENDED",
} as const;

export const MISSION_STATUS = {
  SUBMITTABLE: "SUBMITTABLE",
  SUBMITTING: "SUBMITTING",
  UNSUBMITTABLE: "UNSUBMITTABLE",
  ENDED: "ENDED",
} as const;

// TODO: mission 도메인 상수 별도로 분리
export const MISSION_SUBMISSION_METHOD = {
  PUBLIC_PULL_REQUEST: "PUBLIC_PULL_REQUEST",
  PRIVATE_REPOSITORY: "PRIVATE_REPOSITORY",
} as const;

export const BUTTON_LABEL = {
  BEFORE_SUBMIT: "준비 중",
  EDIT: "수정하기",
  SUBMIT: "제출하기",
  UNSUBMITTABLE: "제출불가",
  COMPLETE: "제출완료",
  UNSUBMITTED: "미제출",
} as const;
