export const RECRUITMENT_STATUS = {
  RECRUITABLE: "RECRUITABLE",
  RECRUITING: "RECRUITING",
  UNRECRUITABLE: "UNRECRUITABLE",
  ENDED: "ENDED",
} as const;

export const MISSION_STATUS = {
  SUBMITTABLE: "SUBMITTABLE",
  SUBMITTING: "SUBMITTING",
  UNSUBMITTABLE: "UNSUBMITTABLE",
  ENDED: "ENDED",
} as const;
